version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    mem_reservation: 2048MB
    cpu_count: 4
    environment:
      MYSQL_DATABASE: stock
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - stock-retriever-docker-network

  app-back:
    build:
      context: ./server
    container_name: app-back
    mem_reservation: 2048MB
    cpu_count: 4
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql-server:3306/stock
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-server:3306/stock
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - stock-retriever-docker-network
    depends_on:
      mysql-server:
        condition: service_healthy

  app-front:
    build:
      context: ./front
    container_name: app-front
    ports:
      - "3000:80"
    networks:
      - stock-retriever-docker-network

networks:
  stock-retriever-docker-network:
    driver: bridge